version: '3'
services:
  flask-app:
    build:
      context: ./python
    ports:
      - "5001:5000"
    environment:
      - DB_NAME=dbname
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerfileDev
    ports:
      - "8080:80"
    depends_on:
      - flask-app
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: yourpassword
    networks:
      - mynetwork

networks:
  mynetwork: